- app/build.gradle
- app/src/main/java/com/example/karaoke_note/AppBar.kt
- app/src/main/java/com/example/karaoke_note/Home.kt
- app/src/main/java/com/example/karaoke_note/MainActivity.kt
- 画面遷移機能を追加
- 画面上部にAppBarを追加
- テストのため、homeにボタンを追加
- homeを別ファイルに切り出し
> Navigation Controlの実装

- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
- app/src/main/java/com/example/karaoke_note/BottomNavBar.kt
- app/src/main/java/com/example/karaoke_note/Home.kt
- app/src/main/java/com/example/karaoke_note/MainActivity.kt
- 画面下部のナビゲーションバーとアーティスト一覧をざっくりと作りました。それだけ。
- NavigationBar の List を押すとアーティスト一覧に飛びます。
- 同 Home で戻ります。
> Artist list

- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
- app/src/main/java/com/example/karaoke_note/Home.kt
- app/src/main/java/com/example/karaoke_note/MainActivity.kt
- app/src/main/java/com/example/karaoke_note/data/AppDatabase.kt
- app/src/main/java/com/example/karaoke_note/data/Song.kt
- app/src/main/java/com/example/karaoke_note/data/migrations/Migration_1_2.kt
アイコンの色情報も保存するため、データベースにカラムを追加しました。
> ArtistのListをデータベースから取得

- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
- app/src/main/java/com/example/karaoke_note/MainActivity.kt
- app/src/main/java/com/example/karaoke_note/SongList.kt
- app/src/main/java/com/example/karaoke_note/data/SongDao.kt
- app/src/main/java/com/example/karaoke_note/data/SongScoreDao.kt
#10 です。
見た目は後回しでとりあえず機能だけ作りました。
> Artists song list

- app/src/main/java/com/example/karaoke_note/MainActivity.kt
- app/src/main/java/com/example/karaoke_note/SongScores.kt
- app/src/main/java/com/example/karaoke_note/data/SongDao.kt
- app/src/main/java/com/example/karaoke_note/data/SongScoreDao.kt
> score削除時に空になった曲は削除する

- app/src/main/java/com/example/karaoke_note/MainActivity.kt
- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
#25 です。
- タイトルとアーティストの初期値をnavControllerのrouteから取るようにした
- それに伴ってinvalidTitleとinvalidArtistの判定タイミングを変更
- インデントがずれている場所があったので修正
> New entry get info

- app/src/main/java/com/example/karaoke_note/Home.kt
#24 
これで、ダミーデータを消しても消しても勝手に復活することはなくなります。
> ダミーデータを追加していたのをやめる

- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
Save ボタンが隠れる件を解消しようとしましたがいい方法が思いつかず、結局新規登録画面のエラーチェックを実装しました。
また、TextField がいっぱいあると手入れが大変なので共通化しました。
> 新規登録時の値チェック

- app/src/main/java/com/example/karaoke_note/SongList.kt
- app/src/main/java/com/example/karaoke_note/data/SongScoreDao.kt
> 最後に歌った日がアーティスト全体での値になっていたので修正

- app/build.gradle
- app/src/main/java/com/example/karaoke_note/AppBar.kt
- app/src/main/java/com/example/karaoke_note/MainActivity.kt
- app/src/main/java/com/example/karaoke_note/data/AppDatabase.kt
- app/src/main/java/com/example/karaoke_note/data/SongDao.kt
- app/src/main/java/com/example/karaoke_note/data/SongScoreDao.kt
> データベースのimport/export

- app/src/main/java/com/example/karaoke_note/AppBar.kt
- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
- app/src/main/java/com/example/karaoke_note/Home.kt
- app/src/main/java/com/example/karaoke_note/MainActivity.kt
- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
- app/src/main/java/com/example/karaoke_note/SongList.kt
- app/src/main/java/com/example/karaoke_note/data/AppDatabase.kt
- app/src/main/java/com/example/karaoke_note/data/Artist.kt
- app/src/main/java/com/example/karaoke_note/data/ArtistDao.kt
- app/src/main/java/com/example/karaoke_note/data/Song.kt
- app/src/main/java/com/example/karaoke_note/data/SongDao.kt
- app/src/main/java/com/example/karaoke_note/data/migrations/Migration_2_3.kt
#58 です。
未検証ですが#57 が解決するかもしれません。
アプリ起動時にマイグレーションが起きますが、念のためV2の時点でエクスポート機能を使ってバックアップを取っておいてください。
> アーティスト情報をSongテーブルから分離 (DBをV2->V3)

- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
#33 のごく一部です。DB にも影響するので、現時点では Save 時に値を渡すことはしていません。
> 採点ゲーム選択メニューを実装しました。

- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
変数 gamesList が newTitle と newGame の間にあったので定義位置を変更。
> 変数 gamesList の場所を変えただけ

- app/src/main/java/com/example/karaoke_note/data/ArtistDao.kt
> 既に存在するArtistを追加しようとした場合、Song同様追加せずIDを返すよう修正

- app/src/main/java/com/example/karaoke_note/SongScores.kt
- app/src/main/java/com/example/karaoke_note/data/SongDao.kt
#55 の一部です。
こんな感じで問題なければアーティストの方もやります。
> 曲名を編集する機能の実装

- app/src/main/java/com/example/karaoke_note/SongList.kt
- app/src/main/java/com/example/karaoke_note/data/ArtistDao.kt
> アーティスト名を編集する機能の実装

- app/src/main/java/com/example/karaoke_note/Breadcrumbs.kt
- app/src/main/java/com/example/karaoke_note/MainActivity.kt
> パンくずリストの実装

- app/src/main/java/com/example/karaoke_note/data/SongScoreDao.kt
> Homeの並び順を変更

- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
- app/src/main/java/com/example/karaoke_note/SongList.kt
- app/src/main/java/com/example/karaoke_note/SongScores.kt
- app/src/main/java/com/example/karaoke_note/data/ArtistDao.kt
- app/src/main/java/com/example/karaoke_note/data/SongDao.kt
#84 です。
アーティストについては「スコアが存在する曲が1曲以上ある」という条件なのでクエリがややこしくなっています。
> 空の曲やアーティストを表示時に隠す

- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
> Listのアーティスト順をデフォルトでソートする

- app/src/main/java/com/example/karaoke_note/data/SongDao.kt
#85 のときに、曲リストに同じ曲が複数個現れるようになっていたため修正します。
> 曲リストの表示時に同じ要素を複数個表示しないよう修正

- app/src/main/java/com/example/karaoke_note/Home.kt
- app/src/main/java/com/example/karaoke_note/SongScores.kt
> キーを上げた曲を登録したとき、リストに + 符号付きで表示するようにした。

- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
- app/src/main/java/com/example/karaoke_note/data/GameKind.kt
ガイドライン的にはアウトでしょうけど視認性はよくなるかなと思います。
あと、バグ修正も入っています。
> グラフィカルなゲーム選択画面

- app/src/main/java/com/example/karaoke_note/BottomNavBar.kt
- app/src/main/java/com/example/karaoke_note/Home.kt
- app/src/main/java/com/example/karaoke_note/MainActivity.kt
- app/src/main/java/com/example/karaoke_note/Plans.kt
> 空の Plans ページを追加

- app/src/main/java/com/example/karaoke_note/Plans.kt
今回はとりあえずレイアウト草案だけ。
今後の課題
リストに 0.00 点で登録した曲だけを表示する。
Card をタップすると編集画面が開く。
> Plan ページのレイアウト案。

- app/src/main/java/com/example/karaoke_note/Breadcrumbs.kt
> パンくずリストで落ちるバグを修正

- app/src/main/java/com/example/karaoke_note/data/SongScoreDao.kt
> PlansのスコアをLatestに表示しないよう修正

- app/src/main/AndroidManifest.xml
> 画面の向きを縦向きに固定

- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
- app/src/main/java/com/example/karaoke_note/ui/component/CommonTextField.kt
#29 でさらにCommonTextFieldが肥大化しそうなので、別ファイルに切り出します。
> CommonTextFieldを別ファイルに切り出し

- app/src/main/java/com/example/karaoke_note/SongScores.kt
- app/src/main/java/com/example/karaoke_note/ui/component/SongScoreDetailDialog.kt
> DetailDialogをスコアに応じた表示になるよう修正

- app/src/main/java/com/example/karaoke_note/Home.kt
- app/src/main/java/com/example/karaoke_note/data/SongScoreDao.kt
> Latestの追加ロードの実装

- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
- app/src/main/java/com/example/karaoke_note/Plans.kt
- app/src/main/java/com/example/karaoke_note/data/ArtistDao.kt
- app/src/main/java/com/example/karaoke_note/data/SongScoreDao.kt
#122 です。
Latestはややこしそうだったのでそれ以外の対応です。
> スコア登録後に画面に即時反映されるようにする修正

- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
> 8色のアーティストアイコンを均等に配置するよう修正。

- app/src/main/java/com/example/karaoke_note/Home.kt
> Latest ページ用の Scroll up ボタンを実装

- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
- app/src/main/java/com/example/karaoke_note/ui/component/CommonTextField.kt
- app/src/main/java/com/example/karaoke_note/ui/component/DatePicker.kt
- app/src/main/java/com/example/karaoke_note/ui/component/GameKindSelector.kt
NewEntrySheet.kt からいくつかの関数を別ファイルに切り出しました。
NewEntrySheet() 内のいくつかの処理を別関数化して本体をスリム化しました。（それでも長いですが）
TextField の値チェックを入力ごとに行うようにしました。
保存時にエラー判定をしてエラーダイアログを表示させるのではなく、そもそも Save ボタンを押せないようにしました。
> NewEntrySheet() のスリム化

- app/src/main/java/com/example/karaoke_note/Home.kt
- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
- app/src/main/java/com/example/karaoke_note/SortableTable.kt
> Plans ページから NewEntrySheet を呼び出したときにスコア欄をクリアする

- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
#132 です。
セーブしたときに false に戻すようにしました。
> 新規登録画面を開いたときの Save ボタンの Enable 判定

- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
> Entry as plans スイッチを True にしたときの Save ボタンの挙動を修正

- app/src/main/java/com/example/karaoke_note/BottomNavBar.kt
- app/src/main/java/com/example/karaoke_note/MainActivity.kt
> plansのアイコンの右上にバッジを表示

- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
- app/src/main/java/com/example/karaoke_note/BottomNavBar.kt
- app/src/main/java/com/example/karaoke_note/MainActivity.kt
- app/src/main/java/com/example/karaoke_note/SortableTable.kt
#36 です。
前にバッジ機能を実装してくれていたので何とかできました。
> アーティストごとの曲数表示

- app/src/main/java/com/example/karaoke_note/BottomNavBar.kt
> Plans 登録曲数が 0 のときはバッジを表示させないように変更

- .idea/gradle.xml
- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
- app/src/main/java/com/example/karaoke_note/MainActivity.kt
- app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
- app/src/main/java/com/example/karaoke_note/Plans.kt
- app/src/main/java/com/example/karaoke_note/SongScores.kt
- app/src/main/java/com/example/karaoke_note/data/SongDao.kt
- app/src/main/java/com/example/karaoke_note/ui/component/CustomSwipeToDismiss.kt
左スワイプすると削除できます。
Undo 機能を作りたいんですがやり方がわからないのでそこは今後の課題ということで。
> Plans カードを削除する機能を作成

- app/src/main/java/com/example/karaoke_note/ui/component/CommonTextField.kt
> テキストフィールドが空のときは補完候補が出ないよう変更

- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
- app/src/main/java/com/example/karaoke_note/SongList.kt
- app/src/main/java/com/example/karaoke_note/SongScores.kt
- app/src/main/java/com/example/karaoke_note/SortableTable.kt
> Ascend / Descend の矢印をアイコン化

- app/src/main/java/com/example/karaoke_note/AllSongList.kt
- app/src/main/java/com/example/karaoke_note/ui/component/SortMethodSelector.kt
https://github.com/co-akuma-voice/karaoke_note/pull/157#pullrequestreview-2065062380 の件です。
> 日付順とスコア順のソートを実装

- app/src/main/java/com/example/karaoke_note/AllSongList.kt
- app/src/main/java/com/example/karaoke_note/AppBar.kt
- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
- app/src/main/java/com/example/karaoke_note/Latest.kt
- app/src/main/java/com/example/karaoke_note/MainActivity.kt
- app/src/main/java/com/example/karaoke_note/data/FilterSetting.kt
- app/src/main/java/com/example/karaoke_note/data/GameKind.kt
- app/src/main/java/com/example/karaoke_note/data/SongScoreDao.kt
#71 の一部です。
とりあえずLatestとAllSongsのみ対象で、曲ごとのスコア一覧とかはまだです。
JOYとDAMの左右サイズを均等にできず諦めたので調整できそうならやってみてください。。
> 採点モードによるフィルタリングの実装

- app/src/main/java/com/example/karaoke_note/AppBar.kt
- app/src/main/java/com/example/karaoke_note/data/FilterSetting.kt
#71 の一環です。
画像は https://github.com/co-akuma-voice/karaoke_note/issues/71#issuecomment-2267441856 参照。
> フィルタがデフォルト状態かどうかでアイコンを変更

- app/src/main/java/com/example/karaoke_note/MainActivity.kt
- app/src/main/java/com/example/karaoke_note/SongList.kt
- app/src/main/java/com/example/karaoke_note/SongScores.kt
#71 はこれで完了のつもりです。
(プルリクここまで細切れにしなくてもよかったな)
> スコア一覧と曲一覧にフィルタを適用

- app/src/main/java/com/example/karaoke_note/Latest.kt
https://github.com/co-akuma-voice/karaoke_note/issues/71#issuecomment-2267551682 です。
> フィルタ結果を踏まえてlatestの追加ロード条件を変更

- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
> アーティストと全曲の数を表示

- app/src/main/java/com/example/karaoke_note/ui/component/CommonTextField.kt
> 補完候補を5件に制限

- app/src/main/java/com/example/karaoke_note/AppBar.kt
> フィルターの子要素を横スクロール形式にしてスペース節約

- app/src/main/java/com/example/karaoke_note/AppBar.kt
> インポート／エクスポートメニューの位置調整

- app/src/main/java/com/example/karaoke_note/AllSongList.kt
- app/src/main/java/com/example/karaoke_note/ArtistsList.kt
- app/src/main/java/com/example/karaoke_note/SongList.kt
- app/src/main/java/com/example/karaoke_note/SongScores.kt
#182 です。latestだけ別の方法で検索を実現していたのでもともとできていました。
> 検索で大文字小文字を無視するよう変更

- app/src/main/java/com/example/karaoke_note/AllSongList.kt
- app/src/main/java/com/example/karaoke_note/Latest.kt
- app/src/main/java/com/example/karaoke_note/Plans.kt
機能的には変わりません。Material3 を更新したからかな？
> 各リストの高さを調節
