app/src/main/java/com/example/karaoke_note/MainActivity.kt, app/src/main/java/com/example/karaoke_note/SongScores.kt
スコア表示用の画面を別ファイルに切り出し、表を実装しました。
見た目の調整はまだですが、現状以下のような見た目です。
=> スコア表示用テーブルを作成

app/src/main/java/com/example/karaoke_note/Home.kt, app/src/main/java/com/example/karaoke_note/MainActivity.kt, app/src/main/java/com/example/karaoke_note/SongScores.kt, app/src/main/java/com/example/karaoke_note/data/SongDao.kt, app/src/main/java/com/example/karaoke_note/data/SongScoreDao.kt
Homeのカードから曲ごとのスコアに遷移するための変更です。
ダミーデータは毎回勝手に追加するようにし、重複したデータは実際にはデータベースに登録しないことにしました。
=> Home card db

.idea/deploymentTargetDropDown.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
#30, #31 への対応です。
・新規登録画面のキャンセル、Saveを押したときにテキストフィールドの内容をクリアするように修正。
・新規登録画面コメント欄の下に Spacer() を入れて疑似的なスクロールをできるようにした。あくまで疑似的なので、もっといい方法があれば改善したい。
=> 新規登録画面のバグ修正

app/src/main/java/com/example/karaoke_note/SongList.kt, app/src/main/java/com/example/karaoke_note/data/SongDao.kt
#28 です。
曲ごとのスコア一覧はすでにすぐ更新される状態でした。
=> アーティスト曲一覧でスコアを追加したときにすぐ更新されるよう修正

app/src/main/java/com/example/karaoke_note/data/GameKind.kt
ミリオンを選択したときだけスコア欄のフォーマットを変えるという手もあるかもしれない。
=> DAM の精密採点 DX ミリオンは 100 点満点ではないため削除した。

app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
#77です。無理やりなので、もっとスマートな方法があれば改めたいです。
=> 時差による新規登録画面での初期日付のずれを修正。

app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt, app/src/main/java/com/example/karaoke_note/data/SongScoreDao.kt
#78 の修正です。
非同期に削除してから追加すると問題が起きるようなので、削除ではなく更新するようにします。
=> スコア編集時に削除->追加ではなく更新するよう変更

app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
=> 新規登録画面を戻るボタンを押して終了させると編集モードを解除できない問題を修正。

app/src/main/java/com/example/karaoke_note/Plans.kt, app/src/main/java/com/example/karaoke_note/data/SongDao.kt, app/src/main/java/com/example/karaoke_note/data/SongScoreDao.kt
#34 の一環。
点数が0のスコアを取得するクエリを追加し、既存のクエリは点数が0のものを含まないようにします。
=> 点数が0のスコアとそうでないスコアを区別するようDBのクエリを変更

app/src/main/java/com/example/karaoke_note/MainActivity.kt, app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt, app/src/main/java/com/example/karaoke_note/Plans.kt
#34 の一環。
アーティストと曲名を現在のページから取得していましたが、Plansページから遷移する場合はその情報がnavControllerからは取れないので素直にスコアから取得するようにします。
日付の取り方が怪しい(タイムゾーン関連で当日にならなかった問題がここにも影響するのかわかっていない)ので見てもらえると助かります。
=> Plansページからスコア登録画面を開く

app/src/main/java/com/example/karaoke_note/MainActivity.kt, app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
#106 です。
Plans ページ直下で FAB をタップしたときのみ、Entry as plans ボタンが True になるようにしました。Plans ページのカードをタップして編集ページが立ち上がった時は False です。
=> FAB を押したときの動作を変更

app/src/main/java/com/example/karaoke_note/ArtistsList.kt, app/src/main/java/com/example/karaoke_note/SongList.kt, app/src/main/java/com/example/karaoke_note/SongScores.kt, app/src/main/java/com/example/karaoke_note/data/Artist.kt, app/src/main/java/com/example/karaoke_note/data/ArtistDao.kt
アーティスト一覧ページにあるアイコンを長押しすると8色の選択肢が出てきます。
ちょっとマジックナンバー化してしまっているのが気になる・・・
ブランチ名が変ですが、元々アーティスト名を変えるところで Dialog を使って同時に変えられるようにしようと思っていたためです。
=> アーティストアイコンの色を変えられるようにした

app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
#117 です。
NewEntryScreen が消えても選択したゲーム情報を記憶するように rememberSaveable を使うようにしました。残るはず。さすがにアプリを落とすと吹き飛びますが。
=> 前回選択したゲームを記憶させる

app/src/main/java/com/example/karaoke_note/MainActivity.kt, app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt, app/src/main/java/com/example/karaoke_note/Plans.kt, app/src/main/java/com/example/karaoke_note/SongList.kt
#121 に対する修正です。
Plans 仮登録データを編集して新規登録する際に SongScore.id = 0 として SongScore.id を自動で振りなおすよう修正しました。これで表示順序は自然になると思います。
=> Plans データを編集した際の登録順序を自然にする

app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
#143 への対応です。
LaunchedEffect の開始きっかけ (key) が3つしか取れないので、思い切ってごっそり変えてみた。
=> 新規登録画面を開いたときに前のデータが残っているバグを修正

app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
#150 への対応です。
Plans ページで新規登録画面を開き、Entry as plans スイッチを切った時に Supporting text の判定をきちんとするように修正しました。
=> Entry as plans スイッチを切った時の表示を修正

app/src/main/java/com/example/karaoke_note/ArtistsList.kt, app/src/main/java/com/example/karaoke_note/Home.kt, app/src/main/java/com/example/karaoke_note/SongList.kt
全曲リストを表示する前準備（本当は全曲リストも実装したかったんだけど）
Jetpack Compose では Segmented Button が Planned なので、疑似的に通常 Button で作成。
アーティストを選択した後の表示（タイトル、ハイスコア、最後に歌った日）にアーティスト名も付けて表示したいところ。
=> 疑似的な SegmentedButton

app/src/main/java/com/example/karaoke_note/Home.kt
#160 の一環です。
derivedStateOf の判定式を変更して Latest ページにある AnimatedScrollUpButton の Recompose 回数を減らしました。
（いっそボタン自体不要だったかな・・・）
なお、LatestList は Recompose 条件がよくわかりませんが、最下部到達時（= loadSongs 実行時）と AnimatedScrollUpButton 変化時に Recompose されるっぽいです。
このうち、AnimatedScrollUpButton の Recompose 回数をかなり減らせたので結構違うんじゃないかな？と思います。
=> AnimatedScrollUpButton の軽量化

app/src/main/java/com/example/karaoke_note/NewEntrySheet.kt
なんか conflict を直したときにおかしくなって機能が消えてしまったのでやり直しました。
（大したコード量じゃないので、あれこれ戻すよりも書き直した方が早いと思って）
=> 新規登録／編集画面での標準戻るキー／ジェスチャーを無効化

app/build.gradle, app/src/main/java/com/example/karaoke_note/AllSongList.kt, app/src/main/java/com/example/karaoke_note/AppBar.kt, app/src/main/java/com/example/karaoke_note/ArtistsList.kt, app/src/main/java/com/example/karaoke_note/BottomNavBar.kt, app/src/main/java/com/example/karaoke_note/MainActivity.kt, app/src/main/java/com/example/karaoke_note/Plans.kt, app/src/main/java/com/example/karaoke_note/SongList.kt, app/src/main/java/com/example/karaoke_note/SongScores.kt, app/src/main/java/com/example/karaoke_note/SortableTable.kt, app/src/main/java/com/example/karaoke_note/data/FilterSetting.kt, app/src/main/java/com/example/karaoke_note/data/GameKind.kt, app/src/main/java/com/example/karaoke_note/ui/component/CommonTextField.kt, app/src/main/java/com/example/karaoke_note/ui/component/CustomSwipeToDismiss.kt, app/src/main/java/com/example/karaoke_note/ui/component/SongScoreDetailDialog.kt, app/src/main/java/com/example/karaoke_note/ui/component/SortMethodSelector.kt, app/src/main/java/com/example/karaoke_note/ui/theme/Theme.kt, build.gradle, gradle/wrapper/gradle-wrapper.properties
前回のバージョンアップに伴って各ファイルにそこそこ大量の Warning が出ていたので、主にそれらの解消をしています。以下、問題点
(1) ExposedDropdownMenuBox() において非推奨になった Modifier.menuAnchor の代替について、サンプルコードを見つけられなかったために残っている。
(2) Plans.kt と CustomSwipeToDismiss.kt にコメントアウトがいっぱいある。一応戻せるように旧来の関数等が残っているので Warning もたくさん出る。(git の機能で戻せよって？慣れないことをすると痛い目に遭う)
(3) CustomSwipeToDismiss() にある Modifier.swipeable は非推奨になった。これを anchoredDraggable で置き換えるようだが、出たばかりでサンプルコードが少なくうまく書けなかったので妥協した。そのせいで velocityThreshold を設定できなくなり、普通の速度感でスワイプすると削除判定されてしまう。
(4) velocityThreshold を設定できるようにするために SwipeToDismissBox.kt を丸ごとコピーする手も考えられたが、なぜかエラーが出てしまうので実現できなかった。
(5) 最後に気付いたが、TopAppBar 左端にあるべき ArrowBack が消えてしまう。どうも検索バーが長くなっているようだが、その辺のコードは変わっていないはず。
=> Warning 除去
